### ISSUE TITLE
Authentication was requested, but the received header has none specified.

### ISSUE THREAD

**Issue by secit-pl** [FreeDSx/SNMP#10]
Hi,

I'm trying to connect to Dell Switch using following code:

```php
$snmp = new SnmpClient([
    'host' => '1.2.3.4',
    'version' => 3,
    'user' => 'user',
    'use_auth' => true,
    'auth_pwd' => 'PWD',
    'auth_mech' => 'md5',
    'use_priv' => true,
    'priv_pwd' => 'PWD',
    'priv_mech' => 'des',
]);

$uptime = $snmp->getValue('1.3.6.1.2.1.1.3.0');
```

But I get the following error:

```
Authentication was requested, but the received header has none specified.
```

The when I'm using the native php method all is ok:

```php
snmp3_get('1.2.3.4', 'user', 'authPriv', 'MD5', 'PWD', 'DES', 'PWD', '1.3.6.1.2.1.1.3.0');
```

Could you please help?

**Comment by ChadSikorra** [comment]
Hello @secit-pl. Thanks for opening this issue. I haven't worked on this library in a bit due to lack of time. I'll try to take a look at this combo of auth over the coming weekend.

**Comment by secit-pl** [comment]
Thank you. I can confirm that connection also works when I'm using the [brexis/phpsnmp](https://github.com/brexis/phpSNMP) bundle.

**Comment by ChadSikorra** [comment]
Apologies for the slow response on this! It's been a crazy 2 months for me personally. I really appreciate the investigate work @kristk! That certainly looks like it could be an issue. I hope to have some time to look at this in the next few days.

**Comment by ChadSikorra** [comment]
@kristk @secit-pl I pushed the following commit: https://github.com/FreeDSx/SNMP/commit/48ca5f6699b5a785ca55d19ad7b2da3c776993a7 . However, I have no good way to test that this fixes the specific issue you're reporting. If you want to give it a try (use `dev-master` in composer for this library) and let me know if it makes a difference. If so I can tag a new version of the library.

**Comment by kristk** [comment]
@ChadSikorra, this new version works in my use case. I have only tested it in in my current environment with equipment from one manufacturer but I would say that it safe to tag a new version. Thanks!

**Comment by secit-pl** [comment]
@ChadSikorra in my use case it also works. IMO it can be released. Thanks!

**Comment by ChadSikorra** [comment]
Thank you both for reporting the issue and testing the fix. I have tagged a new version (0.4.1) and updated the changelog.

**Comment by secit-pl** [comment]
@ChadSikorra did you pushed the tag? I cannot fid it on https://packagist.org/packages/freedsx/snmp and even on https://github.com/FreeDSx/SNMP/tags

**Comment by ChadSikorra** [comment]
> @ChadSikorra did you pushed the tag? I cannot fid it on https://packagist.org/packages/freedsx/snmp and even on https://github.com/FreeDSx/SNMP/tags

Apologies! Forgot to check the button to push tags 😅 It should be out there now.
